@isTest
private class CaptchaUtilTest {

	@isTest(seeAllData=false) public static void unitTest(){
        /*CaptchaUtil.testTemporal1();
        CaptchaUtil.testTemporal2();
        CaptchaUtil.testTemporal3();
        CaptchaUtil.testTemporal4();
        CaptchaUtil.testTemporal5();
        CaptchaUtil.testTemporal6();
        CaptchaUtil.testTemporal7();
        CaptchaUtil.testTemporal8();
        CaptchaUtil.testTemporal9();
        CaptchaUtil.testTemporal10();
        CaptchaUtil.testTemporal11();
        CaptchaUtil.testTemporal12();
        CaptchaUtil.testTemporal13();
        CaptchaUtil.testTemporal14();
        CaptchaUtil.testTemporal15();
        CaptchaUtil.testTemporal16();
        CaptchaUtil.testTemporal17();
        CaptchaUtil.testTemporal18();
        CaptchaUtil.testTemporal19();
        CaptchaUtil.testTemporal20();
        CaptchaUtil.testTemporal21();
        CaptchaUtil.testTemporal22();
        CaptchaUtil.testTemporal23();
        CaptchaUtil.testTemporal24();
        CaptchaUtil.testTemporal25();
        CaptchaUtil.testTemporal26();
        CaptchaUtil.testTemporal27();
        CaptchaUtil.testTemporal28();*/
    }

}