@isTest
private class DataReflectionDefaultTest {

	@isTest(seeAllData=false) public static void unitTest(){
        /*DataReflectionDefault.testTemporal1();
        DataReflectionDefault.testTemporal2();
        DataReflectionDefault.testTemporal3();
        DataReflectionDefault.testTemporal4();
        DataReflectionDefault.testTemporal5();
        DataReflectionDefault.testTemporal6();
        DataReflectionDefault.testTemporal7();
        DataReflectionDefault.testTemporal8();
        DataReflectionDefault.testTemporal9();
        DataReflectionDefault.testTemporal10();
        DataReflectionDefault.testTemporal11();
        DataReflectionDefault.testTemporal12();
        DataReflectionDefault.testTemporal13();
        DataReflectionDefault.testTemporal14();
        DataReflectionDefault.testTemporal15();
        DataReflectionDefault.testTemporal16();
        DataReflectionDefault.testTemporal17();
        DataReflectionDefault.testTemporal18();
        DataReflectionDefault.testTemporal19();
        DataReflectionDefault.testTemporal20();
        DataReflectionDefault.testTemporal21();
        DataReflectionDefault.testTemporal22();
        DataReflectionDefault.testTemporal23();
        DataReflectionDefault.testTemporal24();
        DataReflectionDefault.testTemporal25();
        DataReflectionDefault.testTemporal26();
        DataReflectionDefault.testTemporal27();
        DataReflectionDefault.testTemporal28();*/
    }
}