@isTest
private class ViewReflectionDefaultTest {

	@isTest(seeAllData=false) public static void unitTest(){
        /*ViewReflectionDefault.testTemporal1();
        ViewReflectionDefault.testTemporal2();
        ViewReflectionDefault.testTemporal3();
        ViewReflectionDefault.testTemporal4();
        ViewReflectionDefault.testTemporal5();
        ViewReflectionDefault.testTemporal6();
        ViewReflectionDefault.testTemporal7();
        ViewReflectionDefault.testTemporal8();
        ViewReflectionDefault.testTemporal9();
        ViewReflectionDefault.testTemporal10();
        ViewReflectionDefault.testTemporal11();
        ViewReflectionDefault.testTemporal12();
        ViewReflectionDefault.testTemporal13();
        ViewReflectionDefault.testTemporal14();
        ViewReflectionDefault.testTemporal15();
        ViewReflectionDefault.testTemporal16();
        ViewReflectionDefault.testTemporal17();
        ViewReflectionDefault.testTemporal18();
        ViewReflectionDefault.testTemporal19();
        ViewReflectionDefault.testTemporal20();
        ViewReflectionDefault.testTemporal21();
        ViewReflectionDefault.testTemporal22();
        ViewReflectionDefault.testTemporal23();
        ViewReflectionDefault.testTemporal24();
        ViewReflectionDefault.testTemporal25();
        ViewReflectionDefault.testTemporal26();
        ViewReflectionDefault.testTemporal27();
        ViewReflectionDefault.testTemporal28();*/
    }

}