@isTest
private class ComponentsEnabledBackEndControllerTest {

	@isTest(seeAllData=false) public static void unitTest(){
	/*	ComponentsEnabledBackEndController.testTemporal1();
        ComponentsEnabledBackEndController.testTemporal2();
        ComponentsEnabledBackEndController.testTemporal3();
        ComponentsEnabledBackEndController.testTemporal4();
        ComponentsEnabledBackEndController.testTemporal5();
        ComponentsEnabledBackEndController.testTemporal6();
        ComponentsEnabledBackEndController.testTemporal7();
        ComponentsEnabledBackEndController.testTemporal8();
        ComponentsEnabledBackEndController.testTemporal9();
        ComponentsEnabledBackEndController.testTemporal10();
        ComponentsEnabledBackEndController.testTemporal11();
        ComponentsEnabledBackEndController.testTemporal12();
        ComponentsEnabledBackEndController.testTemporal13();
        ComponentsEnabledBackEndController.testTemporal14();
        ComponentsEnabledBackEndController.testTemporal15();
        ComponentsEnabledBackEndController.testTemporal16();
        ComponentsEnabledBackEndController.testTemporal17();
        ComponentsEnabledBackEndController.testTemporal18();
        ComponentsEnabledBackEndController.testTemporal19();
        ComponentsEnabledBackEndController.testTemporal20();
        ComponentsEnabledBackEndController.testTemporal21();
        ComponentsEnabledBackEndController.testTemporal22();
        ComponentsEnabledBackEndController.testTemporal23();
        ComponentsEnabledBackEndController.testTemporal24();
        ComponentsEnabledBackEndController.testTemporal25();
        ComponentsEnabledBackEndController.testTemporal26();
        ComponentsEnabledBackEndController.testTemporal27();
        ComponentsEnabledBackEndController.testTemporal28();*/
	}

}