@isTest
private class PageUtilTest {

    @isTest(seeAllData=false) public static void unitTest(){
        /*MockUpFactory.setCustomProperties(false);
        PageUtil.testTemporal1();
        PageUtil.testTemporal2();
        PageUtil.testTemporal3();
        PageUtil.testTemporal4();
        PageUtil.testTemporal5();
        PageUtil.testTemporal6();
        PageUtil.testTemporal7();
        PageUtil.testTemporal8();
        PageUtil.testTemporal9();
        PageUtil.testTemporal10();
        PageUtil.testTemporal11();
        PageUtil.testTemporal12();
        PageUtil.testTemporal13();
        PageUtil.testTemporal14();
        PageUtil.testTemporal15();
        PageUtil.testTemporal16();
        PageUtil.testTemporal17();
        PageUtil.testTemporal18();
        PageUtil.testTemporal19();
        PageUtil.testTemporal20();
        PageUtil.testTemporal21();
        PageUtil.testTemporal22();
        PageUtil.testTemporal23();
        PageUtil.testTemporal24();
        PageUtil.testTemporal25();
        PageUtil.testTemporal26();
        PageUtil.testTemporal27();
		PageUtil.testTemporal28();*/
	}

}